export const icons = {
  "question-mark": "v1706872277/icons/question-mark.svg",
  home: "v1699887218/icons/gvqxjxcw07ei2kkmwnes.svg",
  send: "v1699893673/icons/rmvytilpjgvh3pgwc8ph.svg",
  rocket: "v1699894015/icons/u26xm5hteot875ozfnk9.svg",
  edit: "v1699894149/icons/qxlunbg5tfrdherzsvlt.svg",
  hamburger: "v1699895123/icons/jaqdnomtbhqvjcap962u.svg",
  cross: "v1699895179/icons/xigimrbivcaxt4omxamp.svg",
  bell: "v1699895207/icons/ecejtvqerx81prxyxh9b.svg",
  twitter: "v1699895251/icons/bq6a50xtkvnzhltfggzz.svg",
  worksheet: "v1699895300/icons/ez1s6mtpe5jkunnxzvlw.svg",
  facebook: "v1699895330/icons/iojlvh3o5lshy2jupyph.svg",
  share: "v1699895363/icons/agcmduftef3wcla6gzec.svg",
  "arrow-right": "v1707149070/icons/fv0z57zerrioft52dd9n.svg",
  "arrow-down": "v1699954152/icons/wpfmbmwpyfinipg0d61y.svg",
  "arrow-left": "v1707149179/icons/ejrm9dpgpzb7ddbo8z2i.svg",
  "arrow-up": "v1699954152/icons/arrow-up.svg",
  "worksheet-3": "v1699895429/icons/bzhojpjxp9rukdvh7daz.svg",
  "chevron-right": "v1707752509/icons/vk9xxxhnsltsickom6q9.svg",
  save: "v1699895505/icons/rh1ahwwtbemvz0ihluew.svg",
  success: "v1699895534/icons/Icon-Success_aiiprx",
  error: "v1699895534/icons/Icon-Error_r25aza.svg",
  "quiz-3": "v1699895534/icons/zoayhgtrotv32fad7d3k.svg",
  "chevron-down": "v1699953557/icons/botfld6brychmttwtv6u.svg",
  linkedin: "v1699953592/icons/leqneklorqqzb1zo6rf1.svg",
  "magic-carpet": "v1699953622/icons/jifivg9xxm7sb0fjdilm.svg",
  books: "v1699953657/icons/hz4l3iq6i68kazvkvorq.svg",
  "supervision-level": "v1699953696/icons/cwqhknapp3maa4g0t3lj.svg",
  "quiz-white": "v1699953730/icons/gpcehpgr9mqoumsa25xe.svg",
  "additional-material": "v1699953798/icons/ntoq4tqvcm2uj1pajubt.svg",
  "slide-deck-3": "v1699953830/icons/sm92moja9d5utu3cj16c.svg",
  "sign-language": "v1699953861/icons/ns94ozvozzi22enxkx0x.svg",
  external: "v1699953892/icons/hlxmejse3mcr4tqo6t8u.svg",
  "equipment-required": "v1699953925/icons/pw22bdhj2vrzfv2ogi4e.svg",
  "chevron-left": "v1707752509/icons/rbvzan0ozubmr4j0uqdn.svg",
  download: "v1699953991/icons/dk0f6a6hdpzxftjosngn.svg",
  search: "v1704901279/icons/canbi3fuz5fanzom2hvi.svg",
  "chevron-up": "v1699954058/icons/pay71thmhhylj7z28sj1.svg",
  go: "v1699954090/icons/vdzptyvmitylra8x4usy.svg",
  copyright: "v1699954118/icons/boiod3rflocgsnfokyo8.svg",
  project: "v1699954186/icons/zofq5pheud6spnwjpewk.svg",
  "slide-deck": "v1699954241/icons/sjjy5f3g4eciwcuxxr33.svg",
  "content-guidance": "v1699954277/icons/tm3uhcqenaznq4fxys7j.svg",
  tick: "v1699954310/icons/efd3esaor6zqk7seh6kt.svg",
  instagram: "v1699954343/icons/ayfeljric0kkimdymvva.svg",
  dot: "v1699954371/icons/knykdclphkm8lgff4u2g.svg",
  "dot-png": "v1699954394/icons/qecbh291nzwmhcvqayqd.png",
  warning: "v1704901279/icons/zzszodmk7fvxm9xzzg9s.svg",
  "lightbulb-yellow": "v1705078631/icons/q2v4sqxouy1ngcajoavv.svg",
  lightbulb: "v1705078631/icons/zldisxmbff36z68rwcef.svg",
  quiz: "v1705416077/icons/kaaizjcudy0jfgfrrdel.svg",
  video: "v1705416078/icons/wzey1zfxrvv3apeebbf5.svg",
  intro: "v1705662092/icons/pl7bnmb13txese9yxkjv.svg",
  loopdown: "v1699887218/ui-graphics/loopdown.svg",
  "teacher-lesson": "icons/teacher-lesson.svg",
  "teacher-unit": "icons/teacher-unit.svg",
  "move-arrows": "v1709052869/icons/hoddjsgpzkszgvnmn91q.svg",
  info: "v1709052869/icons/Icon_Info_vsx3xi.svg",
  "subject-art": "subject-icons/art.svg",
  "subject-biology": "subject-icons/biology.svg",
  "subject-chemistry": "subject-icons/chemistry.svg",
  "subject-citizenship": "subject-icons/citizenship.svg",
  "subject-gcse-citizenship": "subject-icons/citizenship.svg",
  "subject-core-citizenship": "subject-icons/citizenship.svg",
  "subject-combined-science": "subject-icons/science.svg",
  "subject-communication-and-language":
    "subject-icons/communication-and-language.svg",
  "subject-computing": "subject-icons/computing.svg",
  "subject-computer-science": "subject-icons/computing.svg",
  "subject-core-computing": "subject-icons/computing.svg",
  "subject-computing-non-gcse": "subject-icons/computing.svg",
  "subject-creative-arts": "subject-icons/creative-arts.svg",
  "subject-design-technology": "subject-icons/design-technology.svg",
  "subject-drama": "subject-icons/drama.svg",
  "subject-english": "subject-icons/english.svg",
  "subject-english-grammar": "subject-icons/english-grammar.svg",
  "subject-english-handwriting": "subject-icons/handwriting.svg",
  "subject-english-reading-for-pleasure": "subject-icons/literature.svg",
  "subject-english-spelling": "subject-icons/english-spelling.svg",
  "subject-english-reading-writing-oracy":
    "subject-icons/reading-writing-oracy.svg",
  "subject-expressive-arts-and-design": "subject-icons/creative-arts.svg",
  "subject-french": "subject-icons/french.svg",
  "subject-geography": "subject-icons/geography.svg",
  "subject-german": "subject-icons/german.svg",
  "subject-history": "subject-icons/history.svg",
  "subject-independent-living": "subject-icons/independent-living.svg",
  "subject-latin": "subject-icons/latin.svg",
  "subject-literacy": "subject-icons/english.svg",
  "subject-maths": "subject-icons/maths.svg",
  "subject-music": "subject-icons/music-hollow.svg",
  "subject-numeracy": "subject-icons/numeracy.svg",
  "occupational-therapy": "subject-icons/therapy.svg",
  "subject-personal-social-and-emotional-development":
    "subject-icons/rshe-pshe.svg",
  "subject-physical-development": "subject-icons/physical-development.svg",
  "subject-physical-education": "subject-icons/physical-education.svg",
  "subject-core-physical-education": "subject-icons/physical-education.svg",
  "subject-gcse-physical-education": "subject-icons/physical-education.svg",
  "subject-physical-therapy": "subject-icons/physical-therapy.svg",
  "subject-physics": "subject-icons/physics.svg",
  "subject-religious-education": "subject-icons/religious-education.svg",
  "subject-core-religious-education": "subject-icons/religious-education.svg",
  "subject-gcse-religious-education": "subject-icons/religious-education.svg",
  "subject-rshe-pshe": "subject-icons/rshe-pshe.svg",
  "subject-rshe": "subject-icons/rshe-pshe.svg",
  "subject-science": "subject-icons/science.svg",
  "subject-sensory-integration": "subject-icons/sensory-integration.svg",
  "subject-spanish": "subject-icons/spanish.svg",
  "subject-speech-and-language-therapy":
    "subject-icons/speech-and-language.svg",
  "subject-specialist": "subject-icons/communication-and-language.svg",
  "subject-therapy": "subject-icons/therapy.svg",
  "subject-therapies": "subject-icons/therapy.svg",
  "subject-occupational-therapy": "subject-icons/therapy.svg",
  "subject-understanding-the-world":
    "subject-icons/understanding-the-world.svg",
} as const;

export type IconName = keyof typeof icons;

export const backgrounds = {
  "confetti-pink": "pupil-journey/confetti-pink.svg",
  "confetti-lavender": "pupil-journey/confetti-lavender.svg",
  "confetti-mint": "pupil-journey/confetti-mint.svg",
  "lesson-confetti-green": "pupil-journey/lesson/lesson-confetti-green.svg",
  "lesson-confetti-mint": "pupil-journey/lesson/lesson-confetti-mint.svg",
  "lesson-confetti-pink": "pupil-journey/lesson/lesson-confetti-pink.svg",
  "lesson-confetti-green-lemon":
    "pupil-journey/lesson/lesson-confetti-green-lemon.svg",
  "lesson-confetti-lavender":
    "pupil-journey/lesson/lesson-confetti-lavender.svg",
  "line-pink": "pupil-journey/line-pink.svg",
  "line-lavender": "pupil-journey/line-lavender.svg",
  "line-mint": "pupil-journey/line-mint.svg",
} as const;

export type BackgroundName = keyof typeof backgrounds;
