export const icons = {
  "question-mark": "icons/question-mark.svg",
  home: "icons/home.svg",
  send: "icons/send.svg",
  rocket: "icons/rocket.svg",
  edit: "icons/edit.svg",
  expand: "icons/expand.svg",
  minimise: "icons/minimise.svg",
  hamburger: "icons/hamburger.svg",
  cross: "icons/cross.svg",
  copy: "icons/copy.svg",
  bell: "icons/bell.svg",
  twitter: "icons/twitter.svg",
  worksheet: "icons/worksheet.svg",
  facebook: "icons/facebook.svg",
  share: "icons/share.svg",
  "arrow-right": "icons/arrow-right.svg",
  "arrow-down": "icons/arrow-down.svg",
  "arrow-left": "icons/arrow-left.svg",
  "arrow-up": "icons/arrow-up.svg",
  "worksheet-3": "icons/worksheet-3.svg",
  "chevron-right": "icons/chevron-right.svg",
  save: "icons/save.svg",
  success: "icons/success.svg",
  error: "icons/error.svg",
  filter: "icons/filter.svg",
  "quiz-3": "icons/quiz-3.svg",
  "chevron-down": "icons/chevron-down.svg",
  linkedin: "icons/linkedin.svg",
  "magic-carpet": "icons/magic-carpet.svg",
  books: "icons/books.svg",
  "supervision-level": "icons/supervision-level.svg",
  "quiz-white": "icons/quiz-white.svg",
  "additional-material": "icons/additional-material.svg",
  "slide-deck-3": "icons/slide-deck-3.svg",
  "sign-language": "icons/sign-language.svg",
  external: "icons/external.svg",
  "equipment-required": "icons/equipment-required.svg",
  "chevron-left": "icons/chevron-left.svg",
  download: "icons/download.svg",
  search: "icons/search.svg",
  "chevron-up": "icons/chevron-up.svg",
  go: "icons/go.svg",
  copyright: "icons/copyright.svg",
  project: "icons/project.svg",
  "slide-deck": "icons/slide-deck.svg",
  "content-guidance": "icons/content-guidance.svg",
  tick: "icons/tick.svg",
  instagram: "icons/instagram.svg",
  dot: "icons/dot.svg",
  "dot-png": "icons/dot-png.png",
  warning: "icons/warning.svg",
  "lightbulb-yellow": "icons/lightbulb-yellow.svg",
  lightbulb: "icons/lightbulb.svg",
  quiz: "icons/quiz.svg",
  video: "icons/video.svg",
  intro: "icons/intro.svg",
  loopdown: "ui-graphics/loopdown.svg",
  "teacher-lesson": "icons/teacher-lesson.svg",
  "teacher-unit": "icons/teacher-unit.svg",
  "move-arrows": "icons/move-arrows.svg",
  info: "icons/info.svg",
  play: "icons/play.svg",
  "subject-art": "subject-icons/art.svg",
  "subject-biology": "subject-icons/biology.svg",
  "subject-chemistry": "subject-icons/chemistry.svg",
  "subject-citizenship": "subject-icons/citizenship.svg",
  "subject-gcse-citizenship": "subject-icons/citizenship.svg",
  "subject-core-citizenship": "subject-icons/citizenship.svg",
  "subject-combined-science": "subject-icons/science.svg",
  "subject-communication-and-language":
    "subject-icons/communication-and-language.svg",
  "subject-computing": "subject-icons/computing.svg",
  "subject-computer-science": "subject-icons/computing.svg",
  "subject-core-computing": "subject-icons/computing.svg",
  "subject-cooking-nutrition": "subject-icons/cooking-nutrition.svg",
  "subject-computing-non-gcse": "subject-icons/computing.svg",
  "subject-creative-arts": "subject-icons/creative-arts.svg",
  "subject-design-technology": "subject-icons/design-technology.svg",
  "subject-drama": "subject-icons/drama.svg",
  "subject-english": "subject-icons/english.svg",
  "subject-english-grammar": "subject-icons/english-grammar.svg",
  "subject-english-handwriting": "subject-icons/handwriting.svg",
  "subject-english-reading-for-pleasure": "subject-icons/literature.svg",
  "subject-english-spelling": "subject-icons/english-spelling.svg",
  "subject-english-reading-writing-oracy":
    "subject-icons/reading-writing-oracy.svg",
  "subject-english-vocabulary": "subject-icons/vocabulary.svg",
  "subject-expressive-arts-and-design": "subject-icons/creative-arts.svg",
  "subject-french": "subject-icons/french.svg",
  "subject-geography": "subject-icons/geography.svg",
  "subject-german": "subject-icons/german.svg",
  "subject-history": "subject-icons/history.svg",
  "subject-independent-living": "subject-icons/independent-living.svg",
  "subject-latin": "subject-icons/latin.svg",
  "subject-literacy": "subject-icons/english.svg",
  "subject-maths": "subject-icons/maths.svg",
  "subject-music": "subject-icons/music-hollow.svg",
  "subject-numeracy": "subject-icons/numeracy.svg",
  "occupational-therapy": "subject-icons/therapy.svg",
  "subject-personal-social-and-emotional-development":
    "subject-icons/rshe-pshe.svg",
  "subject-physical-development": "subject-icons/physical-development.svg",
  "subject-physical-education": "subject-icons/physical-education.svg",
  "subject-core-physical-education": "subject-icons/physical-education.svg",
  "subject-gcse-physical-education": "subject-icons/physical-education.svg",
  "subject-physical-therapy": "subject-icons/physical-therapy.svg",
  "subject-physics": "subject-icons/physics.svg",
  "subject-religious-education": "subject-icons/religious-education.svg",
  "subject-core-religious-education": "subject-icons/religious-education.svg",
  "subject-gcse-religious-education": "subject-icons/religious-education.svg",
  "subject-rshe-pshe": "subject-icons/rshe-pshe.svg",
  "subject-rshe": "subject-icons/rshe-pshe.svg",
  "subject-science": "subject-icons/science.svg",
  "subject-sensory-integration": "subject-icons/sensory-integration.svg",
  "subject-spanish": "subject-icons/spanish.svg",
  "subject-speech-and-language-therapy":
    "subject-icons/speech-and-language.svg",
  "subject-specialist": "subject-icons/communication-and-language.svg",
  "subject-therapy": "subject-icons/therapy.svg",
  "subject-therapies": "subject-icons/therapy.svg",
  "subject-occupational-therapy": "subject-icons/therapy.svg",
  "subject-understanding-the-world":
    "subject-icons/understanding-the-world.svg",
  swimming: "subject-icons/swimming.svg",
  "homepage-robot-waving": "homepage/homepage-robot-waving.svg",
  "homepage-three-pupils": "homepage/homepage-three-pupils.svg",
  "homepage-teacher": "homepage/homepage-teacher.svg",
  "homepage-teacher-map": "homepage/homepage-teacher-map.svg",
  "audio-clip-small": "teacher-journey/audio-clip-small.svg",
} as const;

export type IconName = keyof typeof icons;

export const backgrounds = {
  "confetti-pink": "pupil-journey/confetti-pink.svg",
  "confetti-lavender": "pupil-journey/confetti-lavender.svg",
  "confetti-mint": "pupil-journey/confetti-mint.svg",
  "lesson-confetti-green": "pupil-journey/lesson/lesson-confetti-green.svg",
  "lesson-confetti-mint": "pupil-journey/lesson/lesson-confetti-mint.svg",
  "lesson-confetti-pink": "pupil-journey/lesson/lesson-confetti-pink.svg",
  "lesson-confetti-green-lemon":
    "pupil-journey/lesson/lesson-confetti-green-lemon.svg",
  "lesson-confetti-lavender":
    "pupil-journey/lesson/lesson-confetti-lavender.svg",
  "line-pink": "pupil-journey/line-pink.svg",
  "line-lavender": "pupil-journey/line-lavender.svg",
  "line-mint": "pupil-journey/line-mint.svg",
} as const;

export type BackgroundName = keyof typeof backgrounds;
