import { OakTheme } from "./theme";

export const oakDefaultTheme: OakTheme = {
  name: "default",
  uiColors: {
    "text-primary": "black",
    "text-subdued": "grey60",
    "text-error": "red",
    "text-disabled": "grey50",
    "text-link-active": "navy",
    "text-link-hover": "navy110",
    "text-link-pressed": "navy120",
    "text-link-visited": "lavender110",
    "text-inverted": "white",
    "text-success": "oakGreen",
    "text-warning": "amber", // to be deprecated, we don't use warning text anymore
    "text-promo": "lemon",
    "bg-primary": "white",
    "bg-inverted": "black",
    "bg-neutral": "grey20",
    "bg-neutral-stronger": "grey30",
    "bg-btn-primary": "black",
    "bg-btn-primary-hover": "grey60",
    "bg-btn-primary-disabled": "grey50",
    "bg-btn-secondary": "white",
    "bg-btn-secondary-hover": "grey20",
    "bg-btn-secondary-disabled": "grey30",
    "bg-icon": "black", // to be deprecated, use icon-primary instead
    "bg-icon-hover": "grey60", // to be deprecated, use icon-subdued instead
    "bg-decorative1-main": "mint",
    "bg-decorative1-subdued": "mint50",
    "bg-decorative1-very-subdued": "mint30",
    "bg-decorative2-main": "aqua",
    "bg-decorative2-subdued": "aqua50",
    "bg-decorative2-very-subdued": "aqua30",
    "bg-decorative3-main": "lavender",
    "bg-decorative3-subdued": "lavender50",
    "bg-decorative3-very-subdued": "lavender30",
    "bg-decorative4-main": "pink",
    "bg-decorative4-subdued": "pink50",
    "bg-decorative4-very-subdued": "pink30",
    "bg-decorative5-main": "lemon",
    "bg-decorative5-subdued": "lemon50",
    "bg-decorative5-very-subdued": "lemon30",
    "bg-decorative6-main": "amber",
    "bg-decorative6-subdued": "amber50",
    "bg-decorative6-very-subdued": "amber30",
    "bg-interactive-element1": "grey50",
    "bg-interactive-element2": "grey40",
    "bg-correct": "mint50",
    "bg-incorrect": "red30",
    "bg-success": "oakGreen",
    "bg-error": "red",
    "icon-main": "white", // to be deprecated, icon-inverted will be used instead soon
    "icon-inverted": "black", // this will be updated to white once all current occurrences of icon-inverted are replaced with icon-primary
    "icon-disabled": "grey50",
    "icon-brand": "oakGreen",
    "icon-success": "oakGreen",
    "icon-error": "red",
    "icon-warning": "amber",
    "icon-primary": "black",
    "icon-subdued": "grey60",
    "icon-link-active": "navy",
    "icon-link-hover": "navy110",
    "icon-link-pressed": "navy120",
    "icon-link-visited": "lavender110",
    "icon-decorative1": "mint110",
    "icon-decorative2": "aqua110",
    "icon-decorative3": "lavender110",
    "icon-decorative4": "pink110",
    "icon-decorative5": "lemon110",
    "icon-decorative6": "amber",
    "icon-promo": "lemon",
    "border-primary": "black",
    "border-inverted": "white",
    "border-neutral": "grey50",
    "border-neutral-lighter": "grey40",
    "border-neutral-stronger": "grey60",
    "border-brand": "oakGreen",
    "border-success": "oakGreen",
    "border-error": "red",
    "border-warning": "amber",
    "border-decorative1": "mint",
    "border-decorative1-stronger": "mint110",
    "border-decorative2": "aqua",
    "border-decorative2-stronger": "aqua110",
    "border-decorative3": "lavender",
    "border-decorative3-stronger": "lavender110",
    "border-decorative4": "pink",
    "border-decorative4-stronger": "pink110",
    "border-decorative5": "lemon",
    "border-decorative5-stronger": "lemon110",
    "border-decorative6": "amber50",
    "border-decorative6-stronger": "amber",
    transparent: "transparent",
    "code-blue": "rpf-syntax-blue",
    "code-green": "rpf-syntax-green",
    "code-grey": "rpf-syntax-grey",
    "code-pink": "rpf-syntax-pink",
  },
};
