import { OakTheme } from "./theme";

export const oakDefaultTheme: OakTheme = {
  name: "default",
  uiColors: {
    "text-primary": "black",
    "text-subdued": "grey70",
    "text-error": "red",
    "text-disabled": "grey50",
    "text-link-active": "navy",
    "text-link-hover": "navy110",
    "text-link-visited": "navy120",
    "text-inverted": "white",
    "text-success": undefined,
    "text-warning": "red",
    "bg-primary": "white",
    "bg-neutral": "grey20",
    "bg-neutral-stronger": "grey30",
    "bg-btn-primary": "black",
    "bg-btn-primary-hover": undefined,
    "bg-btn-primary-disabled": "grey50",
    "bg-btn-secondary": undefined,
    "bg-btn-secondary-hover": undefined,
    "bg-btn-secondary-disabled": undefined,
    "bg-icon": "black",
    "bg-icon-hover": "grey70",
    "bg-decorative1–main": "mint",
    "bg-decorative1-subdued": "mint50",
    "bg-decorative1-very subdued": "mint30",
    "bg-decorative2-main": "aqua",
    "bg-decorative2-subdued": "mint50",
    "bg-decorative2-very-subdued": "mint30",
    "bg-decorative3-main": "lavender",
    "bg-decorative3-subdued": "lavender50",
    "bg-decorative3-very-subdued": "lavender30",
    "bg-decorative4-main": "pink",
    "bg-decorative4-subdued": "pink50",
    "bg-decorative4-very-subdued": "pink30",
    "bg-decorative5-main": "lemon",
    "bg-decorative5-subdued": "lemon50",
    "bg-decorative5-very-subdued": "lemon30",
    "icon-main": "white",
    "icon-inverted": "black",
    "border-primary": "black",
    "border-inverted": "white",
    "border-neutral": "grey40",
    "border-decorative1": "mint",
    "border-decorative2": "aqua",
    "border-decorative3": "lavender",
    "border-decorative4": "pink",
    "border-decorative5": "lemon",
    "border-decorative6": "amber",
  },
};
