#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git diff-index --quiet HEAD -- || (echo "Error: You have uncommitted changes. Please commit or stash them before pushing." && exit 1)

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "Main Branch push is blocked"
  exit 1
fi

pnpm run check-types
pnpm run test:storybook
pnpm run test:ci
pnpm run build
