#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ "$CI" == "true" ]; then
  echo "Skipping pre-push hook in CI"
  exit 0
fi

git diff-index --quiet HEAD -- || (echo "Error: You have uncommitted changes. Please commit or stash them before pushing." && exit 1)

branch="$(git rev-parse --abbrev-ref HEAD)"

if  [ "$branch" = "main" ]; then
  echo "Main Branch push is blocked"
  exit 1
fi

npm run check-types
npm run test:ci
npm run build
