name: Terraform Drift Detection

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-drift:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run Drift Detection
        uses: oaknational/oak-terraform-actions/actions/terraform-vercel-drift@main
        with:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          TF_CLOUD_ORGANIZATION: ${{ vars.TF_CLOUD_ORGANIZATION }}
          TF_WORKSPACE:         ${{ vars.TF_WORKSPACE }}
          SLACK_WEBHOOK_URL:   ${{ secrets.SLACK_WEBHOOK_URL }}