name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format_and_test:
    name: format, lint, type-check, test and scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb #v6
        with:
          cache: true

      - uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: "pnpm"
          
      - run: pnpm ci
      - run: pnpm run format:check
      - run: pnpm run lint
      - run: pnpm run check-types
      - run: pnpm run build
      - run: pnpm run test:ci
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
